DEVICE: cuda:0               # Training device (cuda, cpu, cuda:0, cuda:1)
SAVE_DIR: 'output'           # Model save directory
DATASET: "0,1"               # datasets' class names form torchvision.datasets

MODEL: "VAN"                 # model name
VARIANT: "L"                 # specific model variants (check by running `python list_models.py`)
PRETRAINED: './output/VAN_L_ImageFolder.pt'
FREEZE: false                # freeze all layers except the last head

IMAGE_SIZE: [224, 224]       # training image size
EVAL_IMAGE_SIZE: [224, 224]  # evaluation image size
EPOCHS: 100                  # number of epochs to train
BATCH_SIZE: 8                # batch size to use
EVAL_INTERVAL: 1             # evaluation interval
AMP: false                   # Mixed Precision Training
LR: 0.0001                   # lr = (batch_size / 1024) * 1e-3
DECAY: 0.005                 # lr decay rate
STEP_SIZE: 2
GAMMA: 0.1